# Generated by Django 3.0 on 2020-06-05 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='upload')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('buat', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data-Seller',
            },
        ),
        migrations.CreateModel(
            name='ProInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesi', models.CharField(max_length=100)),
                ('keahlian', models.CharField(max_length=100)),
                ('pengalaman', models.CharField(max_length=100)),
                ('pendidikan', models.CharField(max_length=100)),
                ('sertifikasi', models.CharField(blank=True, max_length=100, null=True)),
                ('web', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerapp.Seller')),
            ],
        ),
    ]
