# Generated by Django 3.0 on 2020-06-06 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0097_auto_20200605_1936'),
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerProfile', to='tukangkuapp.Profile'),
        ),
    ]
