# Generated by Django 3.0 on 2020-06-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0003_auto_20200606_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proinfo',
            options={'verbose_name_plural': 'Data-Seller'},
        ),
        migrations.AddField(
            model_name='proinfo',
            name='buat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
