# Generated by Django 3.0 on 2020-06-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0005_daftar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daftar',
            new_name='Gigs',
        ),
    ]
