# Generated by Django 3.0 on 2020-06-06 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0098_remove_profile_daftar'),
        ('sellerapp', '0007_auto_20200606_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='gigs',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorGigs', to='sellerapp.ProInfo'),
        ),
        migrations.AddField(
            model_name='proinfo',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellerProfile', to='tukangkuapp.Profile'),
        ),
    ]
