# Generated by Django 3.0 on 2020-06-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0009_auto_20200606_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='proinfo',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
