# Generated by Django 3.0 on 2020-06-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0010_proinfo_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='proinfo',
            name='status',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Client', 'Client,')], default='Client', max_length=30),
        ),
    ]
