# Generated by Django 3.0 on 2020-06-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0012_auto_20200606_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proinfo',
            name='status',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Client', 'Client')], default='Client', max_length=30),
        ),
    ]
