# Generated by Django 3.0 on 2020-06-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0014_proinfo_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proinfo',
            name='author',
        ),
    ]
