# Generated by Django 3.0.7 on 2020-06-07 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellerapp', '0018_auto_20200606_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDirectAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('kirim_ke', models.CharField(blank=True, max_length=254, null=True)),
                ('buat', models.DateTimeField(default=django.utils.timezone.now)),
                ('files', models.FileField(blank=True, help_text='Upload file permintaan anda jika perlu**', null=True, upload_to='')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestAuthor', to=settings.AUTH_USER_MODEL)),
                ('judul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderFrom', to='sellerapp.Gigs')),
            ],
            options={
                'verbose_name_plural': 'Data-Request Author',
            },
        ),
    ]
