# Generated by Django 3.0.7 on 2020-06-07 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0020_auto_20200607_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdirectauthor',
            name='judul',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderFrom', to='sellerapp.Gigs'),
        ),
    ]
