# Generated by Django 3.0.7 on 2020-06-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0021_auto_20200608_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdirectauthor',
            name='judul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderFrom', to='sellerapp.Gigs'),
        ),
    ]
