# Generated by Django 3.0.7 on 2020-06-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0022_auto_20200608_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdirectauthor',
            old_name='files',
            new_name='documen',
        ),
    ]
