# Generated by Django 3.0.7 on 2020-06-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0023_auto_20200608_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdirectauthor',
            old_name='documen',
            new_name='document',
        ),
    ]
