# Generated by Django 3.0.7 on 2020-06-07 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellerapp', '0025_auto_20200608_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdirectauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestAuthor', to=settings.AUTH_USER_MODEL),
        ),
    ]
