# Generated by Django 3.0.7 on 2020-06-07 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellerapp', '0027_auto_20200608_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdirectauthor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestAuthor', to=settings.AUTH_USER_MODEL),
        ),
    ]
