# Generated by Django 3.0.7 on 2020-06-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0028_auto_20200608_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdirectauthor',
            name='slug',
        ),
    ]
