# Generated by Django 3.0.7 on 2020-06-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0029_remove_requestdirectauthor_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigs',
            old_name='deskripsi',
            new_name='deskripsi_singkat',
        ),
    ]
