# Generated by Django 3.0.7 on 2020-06-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0030_auto_20200608_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigs',
            old_name='file',
            new_name='thumbnail',
        ),
    ]
