# Generated by Django 3.0.7 on 2020-06-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0031_auto_20200608_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdirectauthor',
            name='deskripsi',
        ),
        migrations.AddField(
            model_name='requestdirectauthor',
            name='deskripsi_singkat',
            field=models.CharField(blank=True, help_text='Isi deskripsi singkat agar Seller paham dengan permintaan anda**', max_length=500, null=True),
        ),
    ]
