# Generated by Django 3.0.7 on 2020-06-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0032_auto_20200609_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdirectauthor',
            name='paket',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Basic', max_length=30),
        ),
    ]
