# Generated by Django 2.2.10 on 2020-06-15 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0103_auto_20200615_0938'),
        ('sellerapp', '0033_requestdirectauthor_paket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigs',
            old_name='basic',
            new_name='estimasi_besar',
        ),
        migrations.RenameField(
            model_name='gigs',
            old_name='premium',
            new_name='estimasi_kecil',
        ),
        migrations.RemoveField(
            model_name='gigs',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='gigs',
            name='user',
        ),
        migrations.AddField(
            model_name='gigs',
            name='alamat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gigs',
            name='kota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gigs',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorGigs', to='tukangkuapp.Profile'),
        ),
        migrations.AddField(
            model_name='gigs',
            name='provinsi',
            field=models.CharField(choices=[('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh')], default='Aceh', max_length=100),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='buat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='kategori',
            field=models.CharField(choices=[('Kategori', 'Kategori'), ('Arsitek', 'Arsitek'), ('Design Interior', 'Design Interior'), ('Kontraktor', 'Kontraktor'), ('Design and Build', 'Design and Build')], default='Kategori', max_length=50),
        ),
    ]
