# Generated by Django 2.2.10 on 2020-06-15 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellerapp', '0034_auto_20200615_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorGigs', to=settings.AUTH_USER_MODEL),
        ),
    ]
