# Generated by Django 2.2.10 on 2020-06-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0036_auto_20200615_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='proinfo',
            name='deskripsi_singkat',
            field=models.TextField(blank=True, help_text='Deskripsi singkat Profile anda**', null=True),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='deskripsi',
            field=models.CharField(max_length=50),
        ),
    ]
