# Generated by Django 2.2.10 on 2020-06-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0037_auto_20200617_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='waktu_pengerjaan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
