# Generated by Django 2.2.10 on 2020-06-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0038_gigs_waktu_pengerjaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='banyak_revisi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
