# Generated by Django 2.2.10 on 2020-06-18 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0039_gigs_banyak_revisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigs',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usernameGigs', to=settings.AUTH_USER_MODEL),
        ),
    ]
