# Generated by Django 2.2.10 on 2020-06-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0043_albumtukang'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='deskripsi_project',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='upload/display/')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.Gigs')),
            ],
        ),
    ]
