# Generated by Django 2.2.10 on 2020-06-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0045_auto_20200619_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigs',
            name='deskripsi_singkat',
        ),
    ]
