# Generated by Django 2.2.10 on 2020-06-19 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0046_remove_gigs_deskripsi_singkat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usernameGigs', to=settings.AUTH_USER_MODEL),
        ),
    ]
