# Generated by Django 2.2.10 on 2020-06-20 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0047_auto_20200619_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedImageGigs', to='sellerapp.Images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imgGigs', to=settings.AUTH_USER_MODEL),
        ),
    ]
