# Generated by Django 2.2.10 on 2020-06-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0048_auto_20200620_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='buat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
