# Generated by Django 2.2.10 on 2020-06-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0049_images_buat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Data-Seller Gigs Display'},
        ),
    ]
