# Generated by Django 3.0.7 on 2020-06-26 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellerapp', '0050_auto_20200622_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigs',
            name='img',
        ),
        migrations.AddField(
            model_name='images',
            name='gigs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedImageGigs', to='sellerapp.Gigs'),
        ),
        migrations.AlterField(
            model_name='images',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedUseGigs', to=settings.AUTH_USER_MODEL),
        ),
    ]
