# Generated by Django 3.0.7 on 2020-06-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0051_auto_20200626_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
    ]
