# Generated by Django 3.0.7 on 2020-06-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0053_auto_20200626_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='jenis_ruangan',
            field=models.CharField(choices=[('Jenis Ruangan', 'Jenis Ruangan'), ('KT', 'Kamar Tidur'), ('KM', 'Kamar Mandi'), ('D', 'Dapur'), ('RK', 'Ruang Keluarga'), ('Tm', 'Taman'), ('Tg', 'Tangga'), ('Rm', 'Ruang Makan'), ('Ex', 'Exterior'), ('Rb', 'Ruang Belajar'), ('Rk', 'Ruang Kerja'), ('Prep', 'Prepustakaan')], default='Jenis Ruangan', max_length=50),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='status',
            field=models.CharField(choices=[('Dalam antrian', 'Dalam Antrian'), ('Dalam Pengerjaan', 'Dalam Pengerjaan'), ('Selesai', 'Selesai')], default='Client', max_length=30),
        ),
    ]
