# Generated by Django 2.2.10 on 2020-06-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0057_auto_20200628_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
