# Generated by Django 2.2.10 on 2020-06-28 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0058_auto_20200628_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karyawanUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
