# Generated by Django 2.2.10 on 2020-06-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0059_auto_20200628_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='upload/files/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/display/'),
        ),
    ]
