# Generated by Django 2.2.10 on 2020-06-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0060_auto_20200628_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='slug',
        ),
    ]
