# Generated by Django 2.2.10 on 2020-06-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0061_remove_request_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='files',
            field=models.FileField(default='default.jpg', upload_to='upload/files/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='upload/display/'),
        ),
    ]
