# Generated by Django 2.2.10 on 2020-06-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0062_auto_20200628_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
    ]
