# Generated by Django 2.2.10 on 2020-06-29 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0063_auto_20200629_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
