# Generated by Django 2.2.10 on 2020-06-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0068_auto_20200630_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='tanggal_pengerjaan',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='tanggal_selesai',
            field=models.DateField(),
        ),
    ]
