# Generated by Django 2.2.10 on 2020-06-29 18:00

from django.db import migrations, models
import django.db.models.deletion
import sellerapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0069_auto_20200630_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='revisi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('nama_depan', models.CharField(max_length=100)),
                ('nama_belakang', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('kontak', models.CharField(max_length=14)),
                ('deskripsi', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('jenis_ruangan', models.CharField(choices=[('Jenis Ruangan', 'Jenis Ruangan'), ('Kamar Tidur', 'Kamar Tidur'), ('Kamar Mandi', 'Kamar Mandi'), ('Dapur', 'Dapur'), ('Ruang Keluarga', 'Ruang Keluarga'), ('Taman', 'Taman'), ('Tangga', 'Tangga'), ('Ruang Makan', 'Ruang Makan'), ('Exterior', 'Exterior'), ('Ruang Belajar', 'Ruang Belajar'), ('Ruang Kerja', 'Ruang Kerja'), ('Perpustakaan', 'Perpustakaan')], default='Jenis Ruangan', max_length=50)),
                ('files', models.FileField(default='default.jpg', upload_to='upload/files/')),
                ('image', models.ImageField(default='default.jpg', upload_to=None)),
                ('services', models.CharField(choices=[('Kategori', 'Kategori'), ('Arsitek', 'Arsitek'), ('Design Interior', 'Design Interior'), ('Kontraktor', 'Kontraktor'), ('Design and Build', 'Design and Build')], default='Pilihan Service', max_length=50)),
                ('jumlah_budget', models.PositiveIntegerField(default=0)),
                ('alamat', models.CharField(max_length=500)),
                ('kota', models.CharField(max_length=50)),
                ('provinsi', models.CharField(choices=[('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh'), ('Aceh', 'Aceh')], default='Aceh', max_length=50)),
                ('status', models.CharField(choices=[('Dalam antrian', 'Dalam Antrian'), ('Dalam Pengerjaan', 'Dalam Pengerjaan'), ('Selesai', 'Selesai')], default='Dalam Antrian', max_length=30)),
                ('buat', models.DateField(auto_now=True)),
                ('tanggal_pengerjaan', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('komentar', models.TextField()),
                ('kepuasan', models.CharField(choices=[('Puas', 'Puas'), ('Tidak Puas', 'Tidak Puas')], default='Puas', max_length=30)),
                ('emp_id', models.IntegerField(default=sellerapp.models.Invoice.ids, editable=False, unique=True, verbose_name='Code')),
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sellerapp.Request')),
            ],
            options={
                'verbose_name_plural': 'Data - Invoice',
            },
        ),
    ]
