# Generated by Django 2.2.10 on 2020-06-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0070_auto_20200630_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tanggal_pengerjaan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tanggal_selesai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='tanggal_pengerjaan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='tanggal_selesai',
            field=models.DateField(blank=True, null=True),
        ),
    ]
