# Generated by Django 2.2.10 on 2020-06-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0072_auto_20200630_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='kepuasan',
            field=models.CharField(choices=[('Tingkat Kepuasan', 'Tingkat Kepuasan'), ('Puas', 'Puas'), ('Tidak Puas', 'Tidak Puas')], default='Tingkat Kepuasan', max_length=30),
        ),
    ]
