# Generated by Django 2.2.10 on 2020-07-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0074_remove_request_revisi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='komentar',
        ),
        migrations.AddField(
            model_name='request',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
