# Generated by Django 2.2.10 on 2020-07-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0076_auto_20200702_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='provinsi',
            field=models.CharField(max_length=50),
        ),
    ]
