# Generated by Django 2.2.10 on 2020-07-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0077_auto_20200705_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='services',
            field=models.CharField(choices=[('Kategori', 'Kategori'), ('Arsitek', 'Arsitek'), ('Design Interior', 'Design Interior'), ('Kontraktor', 'Kontraktor'), ('Design and Build', 'Design and Build'), ('Lainnya', 'Lainnya')], default='Pilihan Service', max_length=50),
        ),
    ]
