# Generated by Django 2.2.10 on 2020-07-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0078_auto_20200705_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='jenis_ruangan',
            field=models.CharField(choices=[('Jenis Ruangan', 'Jenis Ruangan'), ('Kamar Tidur', 'Kamar Tidur'), ('Kamar Mandi', 'Kamar Mandi'), ('Dapur', 'Dapur'), ('Ruang Keluarga', 'Ruang Keluarga'), ('Taman', 'Taman'), ('Tangga', 'Tangga'), ('Ruang Makan', 'Ruang Makan'), ('Exterior', 'Exterior'), ('Ruang Belajar', 'Ruang Belajar'), ('Ruang Kerja', 'Ruang Kerja'), ('Perpustakaan', 'Perpustakaan'), ('Lainnya', 'Lainnya')], default='Jenis Ruangan', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='services',
            field=models.CharField(choices=[('Kategori', 'Kategori'), ('Arsitek', 'Arsitek'), ('Design Interior', 'Design Interior'), ('Kontraktor', 'Kontraktor'), ('Design and Build', 'Design and Build')], default='Pilihan Service', max_length=50),
        ),
    ]
