# Generated by Django 2.2.10 on 2020-07-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0079_auto_20200705_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='laninnya',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
