# Generated by Django 2.2.10 on 2020-07-05 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0080_request_laninnya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='laninnya',
            new_name='lainnnya',
        ),
    ]
