# Generated by Django 2.2.10 on 2020-07-05 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0081_auto_20200705_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='lainnnya',
            new_name='lainnya',
        ),
    ]
