# Generated by Django 2.2.10 on 2020-07-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0083_auto_20200705_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='image_1',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AddField(
            model_name='request',
            name='image_2',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AddField(
            model_name='request',
            name='image_3',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
    ]
