# Generated by Django 2.2.10 on 2020-07-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0085_auto_20200705_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='kepuasan',
            field=models.CharField(choices=[('Puas', 'Puas'), ('Tidak Puas', 'Tidak Puas')], default='Puas', max_length=30),
        ),
    ]
