# Generated by Django 2.2.10 on 2020-07-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0086_auto_20200705_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='setujui',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Dalam Antrian', 'Dalam Antrian'), ('Dalam Pengerjaan', 'Dalam Pengerjaan'), ('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Selesai', 'Selesai')], default='Dalam Antrian', max_length=30),
        ),
    ]
