# Generated by Django 2.2.10 on 2020-07-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0087_auto_20200705_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='kepuasan',
            field=models.CharField(choices=[('Puas', 'Puas'), ('Tidak Puas', 'Tidak Puas')], default='Puas', max_length=30),
        ),
    ]
