# Generated by Django 2.2.10 on 2020-07-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0088_request_kepuasan'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='revisi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
