# Generated by Django 2.2.10 on 2020-07-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0089_request_revisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='setujui',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
    ]
