# Generated by Django 2.2.10 on 2020-07-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0090_auto_20200706_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='setujui',
            field=models.CharField(choices=[('Beri Persetujuan', 'Beri Persetujuan'), ('Setuju', 'Setuju'), ('Tidak Setuju', 'Tidak Setuju')], default='Beri Persetujuan', max_length=50),
        ),
    ]
