# Generated by Django 2.2.10 on 2020-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0091_auto_20200706_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='upload/display/<django.db.models.fields.related.ForeignKey>/2020/07/06'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_1',
            field=models.ImageField(upload_to='upload/display/<django.db.models.fields.related.ForeignKey>/2020/07/06'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_2',
            field=models.ImageField(upload_to='upload/display/<django.db.models.fields.related.ForeignKey>/2020/07/06'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_3',
            field=models.ImageField(upload_to='upload/display/<django.db.models.fields.related.ForeignKey>/2020/07/06'),
        ),
    ]
