# Generated by Django 2.2.10 on 2020-07-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0092_auto_20200706_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='upload/display/2020/07/06'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_1',
            field=models.ImageField(upload_to='upload/display/2020/07/06'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_2',
            field=models.ImageField(upload_to='upload/display/2020/07/06'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_3',
            field=models.ImageField(upload_to='upload/display/2020/07/06'),
        ),
    ]
