# Generated by Django 2.2.10 on 2020-07-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0095_auto_20200706_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='kepuasan',
            field=models.CharField(blank=True, choices=[('Puas', 'Puas'), ('Tidak Puas', 'Tidak Puas')], default='Puas', max_length=30, null=True),
        ),
    ]
