# Generated by Django 2.2.10 on 2020-07-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0096_auto_20200706_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='bukti',
            field=models.FileField(blank=True, null=True, upload_to='upload/bukti/'),
        ),
    ]
