# Generated by Django 2.2.10 on 2020-07-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0097_request_bukti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='bukti',
            field=models.ImageField(blank=True, null=True, upload_to='upload/bukti/'),
        ),
    ]
