# Generated by Django 2.2.10 on 2020-07-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0099_auto_20200706_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='setujui',
            field=models.CharField(blank=True, choices=[('Beri Persetujuan', 'Beri Persetujuan'), ('Setuju', 'Setuju'), ('Tidak Setuju', 'Tidak Setuju')], default='', max_length=50, null=True),
        ),
    ]
