# Generated by Django 3.1.5 on 2021-01-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0100_auto_20200706_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='upload/display/2021/01/19'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_1',
            field=models.ImageField(upload_to='upload/display/2021/01/19'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_2',
            field=models.ImageField(upload_to='upload/display/2021/01/19'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_3',
            field=models.ImageField(upload_to='upload/display/2021/01/19'),
        ),
    ]
