# Generated by Django 3.1.5 on 2021-01-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0101_auto_20210119_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(upload_to='upload/display/2021/01/20'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_1',
            field=models.FileField(upload_to='upload/display/2021/01/20'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_2',
            field=models.FileField(upload_to='upload/display/2021/01/20'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_3',
            field=models.FileField(upload_to='upload/display/2021/01/20'),
        ),
        migrations.AlterField(
            model_name='request',
            name='bukti',
            field=models.FileField(blank=True, null=True, upload_to='upload/bukti/'),
        ),
    ]
