# Generated by Django 3.0 on 2020-05-08 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('isi', models.TextField()),
                ('image', models.ImageField(default='upload/default-image.jpg', upload_to='upload/')),
            ],
            options={
                'verbose_name_plural': 'Buat-Banner',
            },
        ),
        migrations.CreateModel(
            name='Daftar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(max_length=13)),
                ('deskripsi', models.TextField(blank=True, default='Tidak ada deskripsi', null=True)),
                ('gender', models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=20)),
                ('posisi', models.CharField(choices=[('Mandor', 'Mandor'), ('Kontraktor', 'Kontraktor'), ('Tukang', 'Tukang')], max_length=20)),
                ('buat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Data-Daftar',
            },
        ),
        migrations.CreateModel(
            name='Minta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('perusahaan', models.CharField(max_length=50)),
                ('estimasi', models.CharField(max_length=10)),
                ('deskripsi', models.TextField(blank=True, default='Tidak ada deskripsi', null=True)),
                ('buat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Data-Minta',
            },
        ),
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subjek', models.CharField(blank=True, max_length=100, null=True)),
                ('pesan', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Data-Pesan',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('sub_judul', models.CharField(max_length=200)),
                ('konten', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Buat-Post',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='upload')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data-User',
            },
        ),
    ]
