# Generated by Django 3.0 on 2020-05-09 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tukangkuapp', '0002_auto_20200509_0019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RenameField(
            model_name='minta',
            old_name='perusahaan',
            new_name='kotak',
        ),
        migrations.RenameField(
            model_name='minta',
            old_name='estimasi',
            new_name='upah',
        ),
        migrations.AddField(
            model_name='minta',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='minta',
            name='buat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
