# Generated by Django 3.0 on 2020-05-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0005_auto_20200509_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minta',
            old_name='kotak',
            new_name='kontak',
        ),
    ]
