# Generated by Django 3.0 on 2020-05-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0006_auto_20200509_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
