# Generated by Django 3.0 on 2020-05-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0008_auto_20200510_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftar',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='pesan',
            name='pesan',
        ),
    ]
