# Generated by Django 3.0 on 2020-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0011_auto_20200510_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minta',
            name='upah',
            field=models.CharField(default='Rp ', max_length=50),
        ),
    ]
