# Generated by Django 3.0 on 2020-05-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0012_auto_20200510_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minta',
            name='deskripsi',
        ),
    ]
