# Generated by Django 3.0 on 2020-05-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0013_remove_minta_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='minta',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
