# Generated by Django 3.0 on 2020-05-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0014_minta_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftar',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
