# Generated by Django 3.0 on 2020-05-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0016_daftar_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftar',
            name='nama',
        ),
    ]
