# Generated by Django 3.0 on 2020-05-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0017_remove_daftar_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display',
            field=models.ImageField(default='default.jpg', upload_to='upload/display'),
        ),
    ]
