# Generated by Django 3.0 on 2020-05-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0018_profile_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='upload/default.jpg', upload_to='upload'),
        ),
    ]
