# Generated by Django 3.0 on 2020-05-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0019_auto_20200510_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='upload'),
        ),
    ]
