# Generated by Django 3.0 on 2020-05-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0020_auto_20200510_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='buat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
