# Generated by Django 3.0 on 2020-05-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0022_auto_20200511_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minta',
            options={'verbose_name_plural': 'Data-Request'},
        ),
    ]
