# Generated by Django 3.0 on 2020-05-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0026_auto_20200511_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='deskripsi',
            field=models.TextField(blank=True, help_text='Deskripsikan keahlian anda disini**', null=True),
        ),
    ]
