# Generated by Django 3.0 on 2020-05-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0028_auto_20200511_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='posisi',
            field=models.CharField(choices=[('Mandor', 'Mandor'), ('Kontraktor', 'Kontraktor'), ('Tukang', 'Tukang')], max_length=20),
        ),
    ]
