# Generated by Django 3.0 on 2020-05-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0029_auto_20200511_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='display',
        ),
    ]
