# Generated by Django 3.0 on 2020-05-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0031_profile_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftar',
            name='anggota',
            field=models.CharField(choices=[('Perorangan', 'Perorangan'), ('Team', 'Team')], default='Perorangan', max_length=30),
        ),
    ]
