# Generated by Django 3.0 on 2020-05-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0032_daftar_anggota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='anggota',
            field=models.CharField(choices=[('Perorangan', 'Perorangan'), ('Team', 'Team')], default='Perorangan', help_text='Pilihan anggota atau perorangan**', max_length=30),
        ),
    ]
