# Generated by Django 3.0 on 2020-05-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0037_review_buat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Data-Review'},
        ),
    ]
