# Generated by Django 3.0 on 2020-05-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0039_auto_20200512_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minta',
            name='daftar',
        ),
    ]
