# Generated by Django 3.0 on 2020-05-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0040_remove_minta_daftar'),
    ]

    operations = [
        migrations.AddField(
            model_name='minta',
            name='file',
            field=models.FileField(blank=True, help_text='Upload file permintaan anda jika perlu**', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='minta',
            name='upah',
            field=models.CharField(max_length=50),
        ),
    ]
