# Generated by Django 3.0 on 2020-05-12 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0042_pesanauthor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesanauthor',
            options={'verbose_name_plural': 'Data-Request Pesan Author'},
        ),
        migrations.AddField(
            model_name='pesanauthor',
            name='buat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pesanauthor',
            name='deskripsi',
            field=models.TextField(blank=True, default='haha', null=True),
        ),
        migrations.AddField(
            model_name='pesanauthor',
            name='file',
            field=models.FileField(blank=True, default='haha', help_text='Upload file permintaan anda jika perlu**', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pesanauthor',
            name='judul',
            field=models.CharField(default='haha', max_length=100),
        ),
        migrations.AddField(
            model_name='pesanauthor',
            name='kontak',
            field=models.CharField(default='haha', help_text='Nomor telepon atau email**', max_length=50),
        ),
        migrations.AddField(
            model_name='pesanauthor',
            name='upah',
            field=models.CharField(default='haha', max_length=50),
        ),
    ]
