# Generated by Django 3.0 on 2020-05-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0043_auto_20200512_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanauthor',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesanauthor',
            name='file',
            field=models.FileField(blank=True, help_text='Upload file permintaan anda jika perlu**', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pesanauthor',
            name='judul',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pesanauthor',
            name='kontak',
            field=models.CharField(help_text='Nomor telepon atau email**', max_length=50),
        ),
        migrations.AlterField(
            model_name='pesanauthor',
            name='upah',
            field=models.CharField(max_length=50),
        ),
    ]
