# Generated by Django 3.0 on 2020-05-13 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0044_auto_20200513_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daftar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tukangkuapp.Daftar'),
        ),
    ]
