# Generated by Django 3.0 on 2020-05-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0045_profile_daftar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='daftar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tukangkuapp.Daftar'),
        ),
    ]
