# Generated by Django 3.0 on 2020-05-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0047_auto_20200513_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daftar',
            old_name='author',
            new_name='user',
        ),
    ]
