# Generated by Django 3.0 on 2020-05-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0050_auto_20200513_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftar',
            name='file',
            field=models.FileField(default=1, upload_to='upload/display/'),
        ),
    ]
