# Generated by Django 3.0 on 2020-05-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0052_auto_20200513_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='PostDaftarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tukangkuapp.Daftar')),
            ],
        ),
    ]
