# Generated by Django 3.0 on 2020-05-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0053_auto_20200513_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdaftarimage',
            name='images',
            field=models.FileField(upload_to='upload/display/'),
        ),
    ]
