# Generated by Django 3.0 on 2020-05-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0054_auto_20200513_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daftar',
            old_name='author',
            new_name='user',
        ),
    ]
