# Generated by Django 3.0 on 2020-05-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0055_auto_20200522_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftar',
            name='judul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tukangkuapp.Minta'),
        ),
    ]
