# Generated by Django 3.0 on 2020-05-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0056_daftar_judul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='daftar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tukangkuapp.Daftar'),
        ),
    ]
