# Generated by Django 3.0 on 2020-05-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0057_auto_20200523_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftar',
            name='judul',
        ),
    ]
