# Generated by Django 3.0 on 2020-05-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0058_remove_daftar_judul'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daftar',
            old_name='user',
            new_name='author',
        ),
    ]
