# Generated by Django 3.0 on 2020-05-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0059_auto_20200523_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daftar',
            old_name='author',
            new_name='user',
        ),
    ]
