# Generated by Django 3.0 on 2020-05-25 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0060_auto_20200524_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdaftarimage',
            old_name='post',
            new_name='file',
        ),
    ]
