# Generated by Django 3.0 on 2020-05-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0061_auto_20200525_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftar',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
