# Generated by Django 3.0 on 2020-05-25 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0062_daftar_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftar',
            name='slug',
        ),
    ]
