# Generated by Django 3.0 on 2020-05-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0065_auto_20200525_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='minta',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
