# Generated by Django 3.0 on 2020-05-26 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tukangkuapp', '0066_minta_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='buat',
            field=models.DateTimeField(editable=False),
        ),
        migrations.CreateModel(
            name='RequestDirectAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, help_text='Upload file permintaan anda jika perlu**', null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requestDirect', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data-Request Author',
            },
        ),
    ]
