# Generated by Django 3.0 on 2020-05-26 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0067_auto_20200526_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdirectauthor',
            name='buat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='buat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
