# Generated by Django 3.0 on 2020-05-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0068_auto_20200526_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdirectauthor',
            name='judul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestJudul', to='tukangkuapp.Daftar'),
        ),
        migrations.AddField(
            model_name='requestdirectauthor',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
