# Generated by Django 3.0 on 2020-05-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0069_auto_20200527_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdirectauthor',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
