# Generated by Django 3.0 on 2020-05-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0070_requestdirectauthor_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdirectauthor',
            name='judul',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requestJudul', to='tukangkuapp.Daftar'),
        ),
    ]
