# Generated by Django 3.0 on 2020-05-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0071_auto_20200527_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdirectauthor',
            name='judul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestJudul', to='tukangkuapp.Daftar'),
        ),
    ]
