# Generated by Django 3.0 on 2020-05-27 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tukangkuapp', '0072_auto_20200527_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdirectauthor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestDirect', to=settings.AUTH_USER_MODEL),
        ),
    ]
