# Generated by Django 3.0 on 2020-05-28 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tukangkuapp', '0073_auto_20200527_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdirectauthor',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestAuthor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestdirectauthor',
            name='judul',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='requestdirectauthor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestDirect', to=settings.AUTH_USER_MODEL),
        ),
    ]
