# Generated by Django 3.0 on 2020-06-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0075_auto_20200528_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftar',
            name='upah',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestdirectauthor',
            name='to_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_author', to='tukangkuapp.Profile'),
        ),
    ]
