# Generated by Django 3.0 on 2020-06-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0077_requestdirectauthor_special_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdirectauthor',
            name='special_Request',
            field=models.TextField(blank=True, help_text='Tuliskan permintaan khusus ke author anda disini**', null=True),
        ),
    ]
