# Generated by Django 3.0 on 2020-06-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0079_requestdirectauthor_kirim_ke'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daftar',
            old_name='upah',
            new_name='basic',
        ),
        migrations.AddField(
            model_name='daftar',
            name='premium',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daftar',
            name='standard',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
