# Generated by Django 3.0 on 2020-06-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0081_auto_20200603_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdirectauthor',
            name='special_Request',
        ),
    ]
