# Generated by Django 3.0 on 2020-06-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0088_auto_20200604_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='basic',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='premium',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='standard',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minta',
            name='upah',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
