# Generated by Django 3.0 on 2020-06-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0089_auto_20200604_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minta',
            name='upah',
            field=models.CharField(max_length=50),
        ),
    ]
