# Generated by Django 3.0 on 2020-06-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0094_auto_20200604_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftar',
            name='anggota',
        ),
        migrations.RemoveField(
            model_name='daftar',
            name='posisi',
        ),
        migrations.AddField(
            model_name='daftar',
            name='kategori',
            field=models.CharField(choices=[('Kategori', 'Kategori'), ('Pemrograman & TI', 'Pemrograman & TI'), ('Desain Grafis', 'Desain Grafis'), ('Marketing', 'Marketing'), ('Menulis', 'Menulias'), ('Video & Animasi', 'Video & Animasi'), ('Musik & Audio', 'Musik & Audio'), ('Bisnis', 'Bisnis')], default='Kategori', max_length=50),
        ),
    ]
