# Generated by Django 3.0 on 2020-06-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0095_auto_20200605_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='kategori',
            field=models.CharField(choices=[('Kategori', 'Kategori'), ('Pemrograman & TI', 'Pemrograman & TI'), ('Desain Grafis', 'Desain Grafis'), ('Marketing', 'Marketing'), ('Menulis', 'Menulis'), ('Video & Animasi', 'Video & Animasi'), ('Musik & Audio', 'Musik & Audio'), ('Bisnis', 'Bisnis')], default='Kategori', max_length=50),
        ),
    ]
