# Generated by Django 3.0 on 2020-06-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0097_auto_20200605_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daftar',
        ),
    ]
