# Generated by Django 3.0.7 on 2020-06-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0098_remove_profile_daftar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minta',
            old_name='author',
            new_name='user',
        ),
    ]
