# Generated by Django 2.2.10 on 2020-06-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0105_auto_20200617_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='gambar',
            field=models.ImageField(blank=True, help_text='Masukkan gambar project anda jika perlu**', upload_to='upload'),
        ),
        migrations.AddField(
            model_name='review',
            name='nama',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tukangkuapp.Profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='buat',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
