# Generated by Django 2.2.10 on 2020-06-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0106_auto_20200617_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='nama',
            field=models.CharField(max_length=250),
        ),
    ]
