# Generated by Django 2.2.10 on 2020-06-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0041_remove_gigs_profile'),
        ('tukangkuapp', '0107_auto_20200617_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gigs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileGigs', to='sellerapp.Gigs'),
        ),
    ]
