# Generated by Django 2.2.10 on 2020-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0108_profile_gigs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='keahlian',
        ),
        migrations.AddField(
            model_name='profile',
            name='pendidikan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
