<<<<<<< HEAD
# Generated by Django 3.0.7 on 2020-06-26 13:50
=======
# Generated by Django 2.2.10 on 2020-06-25 16:27
>>>>>>> 0ae2a25b9e33b99652e6c4c854c584ad0408e0fb

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0111_auto_20200622_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanauthor',
            name='nama',
        ),
    ]
