# Generated by Django 2.2.10 on 2020-06-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0112_remove_pesanauthor_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanauthor',
            name='upah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reqUpah', to='sellerapp.Gigs'),
        ),
    ]
