# Generated by Django 3.0.7 on 2020-06-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0113_auto_20200625_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pesanauthor',
            name='upah',
        ),
    ]
