# Generated by Django 3.0.7 on 2020-06-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0115_auto_20200627_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanauthor',
            name='user',
        ),
    ]
