# Generated by Django 2.2.10 on 2020-07-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukangkuapp', '0119_auto_20200702_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PesanAuthor',
        ),
    ]
